### ISSUE TITLE
Pollen (and pollen-users) has adopted Contributor Covenant 2.0

### ISSUE THREAD

**Issue by mbutterick** [mbutterick/pollen-users#108]
Writing about [my situation](https://beautifulracket.com/appendix/why-i-no-longer-contribute-to-racket.html) with Racket management made me reflect on codes of conduct. I believe in them. But I never thought Pollen had a big enough community to warrant one. Nor have there any been any issues (IIRC) that would’ve run afoul of a code of conduct.

But these are characteristic errors of reasoning. I want to correct myself.

The role of the code of conduct is not just to create a framework for adjudicating disputes. It also denotes that a project abides by a “rule of law” — an objective set of principles that others can inspect. 

We are all strangers to each other, with different cultural and language backgrounds. A code of conduct may seem formal, but its main benefit is that it’s *concrete*. Nobody has to guess.

That much I understood.

What I see more clearly now is that a code of conduct does more than arrange interactions among people already participating. It also sends a positive outbound message to individuals who *aren’t* in the project, and who endure more than their fair share of harassment online. (And the only “fair” amount is zero.) The truth is, as a straight white guy, I don’t pay attention to whether a project has adopted a code of conduct because I don’t expect to be on the receiving end. That, however, is just the myopia of privilege. I’d like to fix it. I’m not aware of anyone steering clear of Pollen because of its lack of a code of conduct but — why would that person even tell me? If a code of conduct makes one person in the future feel more comfortable about joining in, it was worth it.

**Comment by otherjoel** [comment]
Assuming the core team continues to avoid addressing the larger issue, perhaps “forked communities” run by others that will actually enforce a CoC are the only way forward on this issue for Racket users.

**Comment by mbutterick** [comment]
My personal experience is emblematic of a larger fault line. Over the years Racket leadership has moved increasingly toward operating as a true open-source project — soliciting & absorbing external contributions (of money & time), joining Software Freedom Conservancy, and so on. Yet their project-management techniques remain rooted in the academic sphere. I think even they would admit that this is *their* myopia. At this point, however, they can’t just retreat into the carapace of research — “go away, we just want to publish papers” — because they’re dependent on that larger community. So they need to find a way to do both things: keep the research side going, but let the open-source side grow and evolve.

Not that anyone asked me, but I think the sanest option is to separate the management of Racket-as-software from Racket-as-research. Obviously there will be individuals who participate in both spheres. But they can be set up in different ways — different governance, different codes of conduct, and so on. (Anyhow, isn’t this what we do in software engineering all the time? Separate  two muddled issues so they can be optimized independently?) Certainly, on the current path, Racket leadership is finding itself getting more athwart its community. The larger the community gets, the more painful this disjunction becomes.

That said, even if some kind of mitotic project split were to happen, I don’t think any community, especially in open source, should ever look to the people in charge to do everything. It’s not realistic. Racket already has a lot of subcommunities of interest that operate away from official channels — `pollen-users` is one of them. It’s an interesting question whether there could be more of a central hub for these communities, like a tilde.club for Racket. That could be fun & interesting — like RacketCon every day. Though “forking” always has a connotation of a irretrievable split in the timeline. I see something like that as supplementary to Racket.
