### ISSUE TITLE
S-Expressions in template.html.p not mapped to tagged X-Expressions in HTML output

### ISSUE THREAD

**Issue by ctittel** [mbutterick/pollen-users#110]
Sorry if this already explained somewhere.

In my `template.html.p` I have the following line:
```lisp
◊(apply ul (for/list ([ii (list 1 2 3)]) ◊li{hello}))
```
In the output (`index.html`) this maps to (no HTML, not what I want):
```
ullihellolihellolihello
```

For testing I also put the same code into `index.html.pm`. In this case it works correctly and maps to
```html
<ul><li>hello</li><li>hello</li><li>hello</li></ul>
```

How do I get the code in the `.p` file to also return HTML Expressions?

**Comment by sorawee** [comment]
Does `◊(->html (apply ul (for/list ([ii (list 1 2 3)]) ◊li{hello})))` work?

**Comment by ctittel** [comment]
Thank you, this works perfectly!
