### ISSUE TITLE
Windows: Set Pollen environment variable

### ISSUE THREAD

**Issue by oldmankit** [mbutterick/pollen-users#128]
In the [pollen docs](https://docs.racket-lang.org/pollen/raco-pollen.html#%28part._.The_.P.O.L.L.E.N_environment_variable%29) it shows how to set the `pollen` environment variable on the command line, like this:
```
POLLEN=DEBUG raco pollen render test.txt ;
```

When I run that in Windows, it doesn't recognise the command `POLLEN`. Here's the error message: `The term 'POLLEN=DEBUG' is not recognized as a name of a cmdlet, function, script file, or executable program.`

I did a search but couldn't find any help on this one. Does anyone know how this is achieved in Windows?

I did try a few variations, like `raco pollen POLLEN=DEBUG render…`, to no avail.

**Comment by odanoburu** [comment]
Apparently you should use something like

```
set POLLEN=DEBUG && raco pollen render test.txt
```

in cmd.exe. If using powershell, it would be another incantation (see https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables?view=powershell-7.2, https://stackoverflow.com/questions/1420719/powershell-setting-an-environment-variable-for-a-single-command-only)

(I don't have a windows machine so I can't test it)
