### ISSUE TITLE
Running pollen on macOS Catalina

### ISSUE THREAD

**Issue by aalexei** [mbutterick/pollen-users#15]
Hi, I'm unable to run a pollen server on macOS Catalina:

/Applications/Racket\ v7.4/bin/raco pollen start

works ok, but if I visit http://localhost:8080 I get the error that the project root was not found (it's definitely there). Presumably this is to do with the new permissions on Catalina. I've tried giving raco and racket full disk access but this did not solve the issues.

Any ideas?

**Comment by mbutterick** [comment]
`cd` into your project directory first. 

Then do `/Applications/Racket\ v7.4/bin/raco pollen start`. 

Same result, or different?

**Comment by aalexei** [comment]
Yes, that's what I had done. Also tried giving the path and port on the command line with same problem. `raco pollen render` works as expected so all the config is fine. 

Is there a way of making the server much more verbose?

**Comment by aalexei** [comment]
Ok, never mind, I'll put it down to user error. `http://localhost:8080/index.ptree` works, it's just a confusing error message. Should perhaps be something like 'index.html' not found instead of saying it can't find the directory.
