### ISSUE TITLE
compiling .pm file for sending to webserver without creating a file

### ISSUE THREAD

**Issue by somesayinice** [mbutterick/pollen-users#24]
Good afternoon. Just wondering if anyone else has tackled a similar problem. I'm trying to publish directly to a website using the website's api. I can connect successfully, get a response with authentication.

However, the data I've been sending is just junk data. What I'm trying to do now is raco pollen render without actually creating a file. I would like to output to a string which I can then send to the webserver for publishing or storage in sql or whatever. Does anyone have any ideas about how to output from a pollen markup file to a string?

I am thinking I should create a *template.api* file and do the work within the template file. Then create a poly-target called api. My only? problem, since ignorance is bliss, is I don't know how to stop the generation of a file.

Thanks much.

**Comment by mbutterick** [comment]
`raco pollen render` is just a convenience for using the underlying [`render`](https://docs.racket-lang.org/pollen/Render.html?q=render#%28def._%28%28lib._pollen%2Frender..rkt%29._render%29%29) function from `pollen/render`. You could call this directly with a source name to get a string.

**Comment by somesayinice** [comment]
Thank you for the quick reply and for the insight. So right now I have four files: pollen.rkt, template.api, test_source.poly.pm, api_test.rkt. Runing the api_test.rkt allows me to get the string output I desire and of course I can send this output to the website api. 
`#lang racket
(require pollen/tag pollen/decode pollen/render pollen/setup txexpr hyphenate racket/runtime-path racket/format racket/string racket/list racket/port net/base64 2htdp/image net/uri-codec net/url net/http-client net/cgi racket/provide json pollen/file sugar pollen-tfl/pollen pollen/template)

(define source-file (build-path (current-directory) "test_source.poly.pm"))
(current-poly-target 'api)
(render source-file)`
But as you can see from the code, it is not dynamic so I'm not sure how to use it without manually editing this .rkt every single time. Ideally, I'd be able to place this in pollen.rkt so that I can build from sublime and it would process the .pm file and send the data to the website. But this doesn't seem to make any sense.

Thanks again for the help. I'll keep bashing along.

**Comment by somesayinice** [comment]
> `raco pollen render` is just a convenience for using the underlying [`render`](https://docs.racket-lang.org/pollen/Render.html?q=render#%28def._%28%28lib._pollen%2Frender..rkt%29._render%29%29) function from `pollen/render`. You could call this directly with a source name to get a string.

I jury-rigged the dry run feature to trigger the render from commandline. This doesn't generate the file and works in my workflow. And it is also likely a very bad way to solve the problem. I am open to learning how to do it better.

**Comment by mbutterick** [comment]
I think I understand — you want to use `raco pollen render` to cause I/O side effects, but not leave behind any files. I suppose we could add a switch for this purpose. Is there a common terminology for this behavior in other command-line tools?

**Comment by somesayinice** [comment]
That is exactly what I was trying to do. I'm not sure what the terminology
is though with other command-line tools. But if dry-run means printing
affected file, maybe a term like console-output might work?
Thanks much again. Your help have made a big difference.

**Comment by mbutterick** [comment]
I have added this option. It is called `--null` or `-n` and will suppress the file output of a render:

`raco pollen render -n foo.html`

**Comment by mbutterick** [comment]
Added by https://github.com/mbutterick/pollen/commit/fc5ca9f65928a581b2545edf71a3201dab807883

**Comment by somesayinice** [comment]
> I have added this option. It is called `--null` or `-n` and will suppress the file output of a render:
> 
> `raco pollen render -n foo.html`

Thanks so much!
