### ISSUE TITLE
PDF accessibility

### ISSUE THREAD

**Issue by sorawee** [mbutterick/pollen-users#29]
Because there's no quad-users, I decide to post this here, but feel free to move it wherever you think appropriate.

Last week, my friend spent an entire day trying to fix accessibility issues in her PDF files generated from LaTeX. By that, I mean making sure that screen reader will say the right thing. The issue is really frustrating because LaTeX source files have all information that is needed to make PDF accessible, but the final output is not accessible at all. 

Can quad generate accessible PDF files? And if not, can I propose to add this to the feature request list?

**Comment by mbutterick** [comment]
It’s already been identified [as a project](https://github.com/mbutterick/quad/projects/1), prompted by [this thread](https://github.com/mbutterick/quad/issues/3) (also critiquing LaTeX).

**Comment by sorawee** [comment]
Thanks!
