### ISSUE TITLE
not insert <br> for single linebreak

### ISSUE THREAD

**Issue by adamfeuer** [mbutterick/pollen-users#41]
Hi,

Is there a way to get pollen to not insert `<br>` tags for single linebreaks? That way I can write text with linebreaks in my editor, but use CSS to flow text when it gets rendered to html.

Right now if I enter this:

```
◊p{First sentence.
Second sentence.
Third sentence.}
```

I get this output: 
```
<p>First sentence<br>
Second sentence.<br>
Third sentence.</p>
```

But I want this: 
```
<p>First sentence Second sentence. Third sentence.</p>
```

**Comment by otherjoel** [comment]
Yes, there is a way to do this; in fact, the desired behavior you describe is the default behavior unless you write code to change it. Are you by chance using [`decode-paragraphs`](https://docs.racket-lang.org/pollen/Decode.html#%28def._%28%28lib._pollen%2Fdecode..rkt%29._decode-paragraphs%29%29) in your `pollen.rkt` or other required modules?

**Comment by adamfeuer** [comment]
@otherjoel Yes, here's an excerpt from my `pollen.rkt`:

```
(define (root . elements)
 (txexpr 'root empty (decode-elements elements
   #:txexpr-elements-proc decode-paragraphs
   #:string-proc (compose1 smart-quotes smart-dashes))))
```

I'm a pollen and racket newbit, so I'm not sure what all that does. I put that together after reading the pollen tutorials...

**Comment by adamfeuer** [comment]
@otherjoel Ah, I see. The `root` tag function is decoding everything when it shouldn't. If I take  out the `decode-paragraphs` pollen now does what I want.

When is the right time to add `decode-paragraphs`? Where is it usually used?

**Comment by mbutterick** [comment]
By default, `decode-paragraphs` will also invoke the default `decode-linebreaks` for single newlines. If you don’t want that behavior, you can supply a `#:linebreak-proc` procedure that will just leave them alone. For instance:

```racket
#lang racket
(require pollen/decode rackunit)

(check-equal?
 (decode-paragraphs '("para1" "\n\n" "para2 line1" "\n" "para2 line2"))
 '((p "para1") (p "para2 line1" (br) "para2 line2")))

(check-equal?
 (decode-paragraphs '("para1" "\n\n" "para2 line1" "\n" "para2 line2")
                    #:linebreak-proc (λ (x) x))
 '((p "para1") (p "para2 line1" "\n" "para2 line2")))
```

You could also replace the linebreaks with a single space `" "`. Note, however, that you wouldn’t want to delete them entirely, because the resulting HTML would be rendered without any space between lines (try it and see).

**Comment by adamfeuer** [comment]
@otherjoel @mbutterick Thank you both!
