### ISSUE TITLE
suggestions for Pollen GUI app?

### ISSUE THREAD

**Issue by mbutterick** [mbutterick/pollen-users#44]
As a way of learning a little about Racket’s GUI library, I’m working on a small app for handling certain Pollen operations without the command line (for instance, running the project server). 

This isn’t going to become the primary interface to Pollen. But it might be useful to people who don’t spend a lot of time on the command line. 

Suggestions welcome for functionality that would be useful.

**Comment by otherjoel** [comment]
A GUI app should be able to provide most of the same functionality as `raco pollen` commands. So, maybe:

* A way to view logs, optionally [at “debug” level](https://github.com/mbutterick/pollen-users/issues/36#issuecomment-599738033) for the `debug@pollen` topic and maybe a user-defined topic.
* A “publish to desktop folder” button.

I’m having a hard time thinking of what a GUI app could give me that is difficult in the command line though. Maybe quick restarts in cases where that is needed (for instance, after editing a pagetree file)?

**Comment by odanoburu** [comment]
Pollen has great potential for building textual DSLs, because it makes implementing them very easy. Some of the users of these DSLs might not be comfortable with CLIs, so I think that any GUI app that's easy to install and allows users to have a WYSIWYG experience would be nice to have! we have [pollen-rock](https://github.com/lijunsong/pollen-rock) already, but I don't how easy it is to install (and it's not native).

**Comment by odanoburu** [comment]
now that I think of it (and it's obvious in retrospect) what I would like to see for beginners might be implemented on top of DrRacket; just adding a preview file button or something similar would be nice! some way of hiding DrRacket functionality that might be scary might be nice to, but might be difficult to implement and maintain.

**Comment by otherjoel** [comment]
Just thought of something. It would be nice to have some help managing and linking to images (or any other type of binary asset) in a Pollen project. Things like:

* Drag/drop files and have them dropped into a particular subfolder of a project
* Optional racket programs/scripts to run post-import
* List, browse and preview binary assets (images, sound, etc.)
* Generate tags that “link” to a file, with quick copy/paste for insertion into Pollen documents. The name of the tag and placement of the filename would need to be customizable on a per-project basis, of course.
