### ISSUE TITLE
Suggestion: Add example of keyword arguments function near section "7.3.3 Attributes" of the doc

### ISSUE THREAD

**Issue by arnaudchenyensu** [mbutterick/pollen-users#55]
Keyword arguments are introduced at [section 7.3.3](https://docs.racket-lang.org/pollen/third-tutorial.html?q=pollen#%28part._.Attributes%29) but no examples are given on how to use it with a function.

Being new to Pollen and Racket, it took me a while to find out how to do it at [section 13.1.6](https://docs.racket-lang.org/pollen/programming-pollen.html?q=pollen#%28part._.Parsing_attributes%29) using `define-tag-function`.

What would you think of adding an example near [section 7.3.3](https://docs.racket-lang.org/pollen/third-tutorial.html?q=pollen#%28part._.Attributes%29)?

**Comment by mbutterick** [comment]
Good idea. Done.
