### ISSUE TITLE
Small problem working through quickstart

### ISSUE THREAD

**Issue by joshstaiger** [mbutterick/pollen-users#70]
Hello,

I'm working through the [quick tour](https://docs.racket-lang.org/pollen/quick-tour.html).  All's well until I get down to the _2.9 Template_ section.

Following the instructions, I create a file named `template.html` with the correct content in the correct directory.  

I navigate to http://localhost:8080/uptown.html. And … nothing changes.

I restart the project server and still nothing changes.

At some point I (accidentally?) re-save the `uptown.html.pm` file and finally the template file is picked up by pollen.

I've also noticed running `raco pollen reset` and restarting the project server also causes the template file to get picked up.

There seems to be an edge-case where when a new template file is added, it isn't picked up by the project server until the files that would use it are "touched". 

At very least, the quick tour should be updated with a mention of re-saving the file to trigger the update.

I'm on Windows 10 if that matters.

**Comment by mbutterick** [comment]
I agree that should work. I’ve fixed it [here](https://github.com/mbutterick/pollen/commit/d96a9d98091fd3564d70f4611f4cf04f98deca63).
