### ISSUE TITLE
Travis CI: the party’s over

### ISSUE THREAD

**Issue by mbutterick** [mbutterick/pollen-users#75]
I have gathered, roughly, that at the end of the year, Travis CI is ending its free testing service for open-source projects. Questions:

1. True?
2. What”s the simplest alternative?

**Comment by sorawee** [comment]
IIUC, they didn't end their free service, but you need to keep applying for more minutes, which is not good.

You can use GitHub Actions as an alternative. Bogdan's https://github.com/Bogdanp/setup-racket might be helpful. You can see how it's setup at [`htdp`](https://github.com/racket/htdp/blob/master/.github/workflows/ci.yml) as an example.
