### ISSUE TITLE
List Processing

### ISSUE THREAD

**Issue by pmenair** [mbutterick/pollen-users#91]
I have a list that I have made by consing strings from various places in a pollen document, called "agenda-dl." If I insert the tag 

◊(for-each (lambda (x) (format "~a\n" x)) agenda-dl) 

I can see the results formatted correctly in the REPL, but it does not appear in the html document. This does not appear to be an output port issue, because 

◊(format "~a" agenda-dl) 

puts me the unquoted strings in parens in the html without newlines, as expected. Is it not possible for a tag to walk through a list of strings in Pollen?

**Comment by mbutterick** [comment]
The return value of `for-each` is always `void`. Maybe you want `map`?

**Comment by pmenair** [comment]
BTW format stopped working so I switched to printf and that was doing the same thing: working in the REPL but not rendering into html. If I switch to map I get:

decode-elements: contract violation
  expected: txexpr-elements?
  given: '({OMITTED BUT SEEMS TO REFERENCE THE WHOLE DOCUMENT IN X-EXPRESSION}...
  in: the 1st argument of
      (->*
       (txexpr-elements?)
       (#:block-txexpr-proc
        (->
         block-txexpr?
         (or/c txexpr-element? txexpr-elements?))
        #:cdata-proc
        (->
         cdata?
         (or/c txexpr-element? txexpr-elements?))
        #:entity-proc
        (->
         (or/c symbol? valid-char?)
         (or/c txexpr-element? txexpr-elements?))
        #:exclude-attrs
        txexpr-attrs?
        #:exclude-tags
        txexpr-tags?
        #:inline-txexpr-proc
        (->
         txexpr?
         (or/c txexpr-element? txexpr-elements?))
        #:string-proc
        (->
         string?
         (or/c txexpr-element? txexpr-elements?))
        #:txexpr-attrs-proc
        (-> txexpr-attrs? txexpr-attrs?)
        #:txexpr-elements-proc
        (-> txexpr-elements? txexpr-elements?)
        #:txexpr-proc
        (->
         txexpr?
         (or/c txexpr-element? txexpr-elements?))
        #:txexpr-tag-proc
        (-> txexpr-tag? txexpr-tag?))
       (or/c txexpr-element? txexpr-elements?))
  contract from: 
      <pkgs>/pollen/pollen/decode.rkt

Have to say I find these txexpr errors kinda unhelpful. But I guess it means I'm getting closer, in that what seems to be happening is it's actually trying to print the list but pollen is having trouble making properly formed x-expressions out of it?

**Comment by pmenair** [comment]
Strings contain literal "[", could that be the problem?

**Comment by pmenair** [comment]
In the REPL, map gives me the strings and then it prints a list of 
'(#<void>
  #<void>
  #<void>
  #<void>
  #<void>
  #<void>
  #<void>
  #<void>
  #<void>
  #<void>
  #<void>
  #<void>
  #<void>
  #<void>)
That's what's throwing the error, I'm sure.

**Comment by pmenair** [comment]
(map (lambda (x) (format "~a\n" x)) agenda-dl) returns a list of strings in the REPL with \n's added and throws a error in the pollen server. ("Expected: txexpr-elements? Given: {a big s-expression that looks like my whole document}."] (map (lambda (x) (format "~a\n" x)) agenda-dl) prints out the strings as desired in the REPL and then returns a quoted list of "#<void>"s in the REPL. It returns a similar error in the pollen server. Looks like this is closer in that *something* is being inserted into the document that is making txexpr unhappy...

**Comment by otherjoel** [comment]
Can you paste a short example pollen source that triggers the problem and the resulting s-expression?

**Comment by pmenair** [comment]
Not exactly, because it's confidential. The individual strings in agenda-dl are in the format "[2021-02-26 Fri]: [ClientName] entry text." The s-expression in the error statement starts "given: '((h1 "Client Matters") "\n" "\n"..." and goes on from there; like with most of the txexpr errors I've been seeing, it seems to just be the whole document translated into one big s-expression, which is expected but not especially helpful when you're trying to localize a problem, although here I'm pretty sure I know where the problem is. The "In:" part of the error is: "in: the 1st argument of
      (->*
       (txexpr-elements?)
       (#:block-txexpr-proc
        (->
         block-txexpr?"

**Comment by mbutterick** [comment]
> (map (lambda (x) (format "~a\n" x)) agenda-dl) returns a list of strings

You can’t return a list of X-expressions (for instance, strings) in a position that Pollen expects a single X-expression. You need to manufacture a new tagged X-expression with the list of X-expressions as elements. To do that, you can wrap the list, either with an HTML tag (like `div`), or, if you really want the list to be merged with the surrounding material, with the special [splicing tag `@`](https://docs.racket-lang.org/pollen/Core.html?q=splicing#%28part._.Splicing%29).

> (map (lambda (x) (printf "~a\n" x)) agenda-dl) prints out the strings as desired in the REPL and then returns a quoted list of voids

Right, because the return value of `printf` is always `void`. If you want to debug expressions, I suggest using the [`debug` language](https://docs.racket-lang.org/debug/index.html), which lets you print expressions without using `printf` statements and disrupting the return value chain.

**Comment by pmenair** [comment]
Got it! Thank you.

**Comment by pmenair** [comment]
Works, sort of. Each string is formatted as " "~a: [~a] ~a \n\n"

◊(txexpr 'div '() agenda-dl)
and
◊(txexpr 'div '() (decode-elements agenda-dl #:txexpr-elements-proc decode-paragraphs))

both give me the text without line or paragraph breaks. I'm guessing that the "\n\n" needs to be a separate element?

**Comment by mbutterick** [comment]
Yes. This is noted [in the docs](https://docs.racket-lang.org/pollen/Decode.html?q=decode-paragraphs#%28def._%28%28lib._pollen%2Fdecode..rkt%29._decode-paragraphs%29%29): “What counts as a paragraph? Any elements that are either a) explicitly set apart with a paragraph separator, or b) adjacent to a block-txexpr? (in which case the paragraph-ness is implied).“

FWIW, instead of embedding newlines in your strings and using `decode-paragraphs`, you could just `map` a tag function:

```
(require pollen/tag)
(map (default-tag-function 'p) '("string1" "string2" "string3"))
```

```
'((p "string1") (p "string2") (p "string3"))
```

**Comment by pmenair** [comment]
Nice! I *just* got it working on my own, with much consing and flattening and decoding... Mapping the tag looks handier :)

**Comment by mbutterick** [comment]
FWIW the reason paragraph decoding works this way is so it cooperates nicely with the Pollen-style curly-brace notation, which returns a list of strings, with linebreaks separated from the other text elements. For instance markup written like so:

```
#lang pollen/mode racket

◊list{
first item

second item

third item
}
```

Results in this:

```
'("first item" "\n" "\n" "second item" "\n" "\n" "third item")
```

Notice that the leading and trailing whitespace is automatically trimmed, as well. Now we can take the output and pass it to `decode-paragraphs`:

```
(decode-paragraphs '("first item" "\n" "\n" "second item" "\n" "\n" "third item"))
```

And get a list of three paragraphs:

```
'((p "first item") (p "second item") (p "third item"))
```

**Comment by pmenair** [comment]
Got it.
