### ISSUE TITLE
Pollen Documentation Moved?

### ISSUE THREAD

**Issue by umj95** [mbutterick/pollen-users#92]
My apologies if this is not the right forum to post this question, but could it be that the pollen documentation has moved/is down? I just started a few days ago to work through the tutorials but since yesterday (I think) I cannot reach the site any more (via https://docs.racket-lang.org/pollen), it always gives me this cryptic error message: "**Page Not Found** `((uncaught-exception-handler) (*(+(*)(*(+(*)(*)(*)(*)(*))(+(*)(*)(*)(*)(*))(+(*)(*)(*)(*))))(+(*)(*)(*)(*)))) uncaught exception: 404`". Curiously, pollen is also no longer listed on the Racket Documentation front page (where I think I found it previously), the only pollen related thing there is pollen-count. Has the page been moved somewhere and I am just too stupid to find it? Or is it just temporarily gone due to some error?
Again, I am sorry if I missed the obvious or used the wrong forum, but has anyone got an idea as to what might have happened?
Thank you so much in advance!

**Comment by sorawee** [comment]
This occurs because of https://github.com/stamourv/sexp-diff/pull/9.

**Comment by mbutterick** [comment]
The documentation is installed locally. Try `raco docs pollen` at the command line, or in DrRacket, `Help > Racket Documentation`

**Comment by umj95** [comment]
Thank you so much for the quick replies! In my panic I completely forgot that there is also local documentation – I guess it tells you something about how much pollen got me hooked... Anyways, glad to hear that it is just a temporary glitch, and the local docs work perfectly fine.
